### ISSUE TITLE
incorrectly formatted station_event_ID in 7. CTD INFO table

### ISSUE THREAD

**Issue by Br-Johnson** [international-year-of-the-salmon/2022-shimada-data-template#2]
Hey @shaunwbell 

I was just working through the Shimada CTD data to integrate it with the other vessels when I noticed I couldn't match most of the measurements in the 7. CTD INFO table to the CTD events in the 4. SAMPLING EVENT INFO table.

The Station_Event_ID is the issue. It looks like when you addressed this issue in your previous pull request that the formatting of the Station_Event_ID wasn't quite right. 

Specifically, it looks like the station component of the Station_Event_ID was limited to only one character. So for example station 10 just appears as station 1 in the Station_Event_ID. 

That is to say for example you ended up with `IYS2022-Shimada-4-1-014-CTD` rather than `IYS2022-Shimada-4-10-014-CTD`. I suspect it's an error in you excel formula somewheres.

Can you confirm this is the case, and if you're so inclined submit another PR? 

Thanks!
Brett

**Comment by shaunwbell** [comment]
@Br-Johnson - I see your point and I suspect you are correct.  I'll take a moment to fix this. expect a pull request shortly.

excel and I have a tenuous relationship at best 😆
